name: Validation

on: [push]

jobs:
  pylint_bandit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cache/pip
          key: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint bandit
          pip install -r ./src/container/pip/requirements.txt
          pip install https://github.com/IBM/qpylib/releases/download/2.0.3/qpylib-2.0.3-py3-none-any.whl
      - name: Analysing the code with pylint
        id: pylint
        continue-on-error: true
        run: |
          mkdir output
          echo "---------------------------PyLint Report---------------------------">> output/python_check.txt
          pylint ./ >> output/python_check.txt
      - name: Analysing the code with bandit
        id: bandit
        continue-on-error: true
        run: |
          echo "---------------------------Bandit Report---------------------------">> output/python_check.txt
          bandit -r ./ -v >> output/python_check.txt
      - name: Security check report artifacts
        uses: actions/upload-artifact@v1
        # if: failure()
        with:
          name: Security report
          path: output/python_check.txt
      - name: Check for failure and report
        if: steps.pylint.outcome != 'success' || steps.bandit.outcome != 'success'
        run: exit 1